server:
  port: ${PORT:9402}
spring:
  application:
    name: gateway-api-service
sidecar:
  port: ${SIDECAR_PORT:9402}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9401/eureka/
